### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bytesofpie** [remoteoss/phx_gen_solid#2]
## Features
- [ ] Support for also calling builtin phx generators (e.g. phx.gen.json)
  - This could be accomplished by having a `--builtin` flag or similar to signal us to call the builtin generator before ours
  - We could even just use `phx.gen.solid.json` as the command
  - Because we use the same format for our generators we should be able to _forward_ the params.
- [ ] Add support for Finders (think ListAllOfEntity, maybe pagination?)
- [x] #3 
- [ ] Add support for Handlers
  - Still need to think about the design for these, e.g. what should be the default scaffolding?
- [ ] `mix phx.gen.solid` should essentially be `phx.gen.json` with all the services, values, finders, and handlers, wired up. One command to generate a schema/migration all the way up to the new endpoint being wired up. You should be able to perform CRUD operations on a new entity after this single command.
- [x] Generate tests for all of the above

**Comment by ditorodev** [comment]
Is this still being worked on? Seems like there's no real updated to the plugin, it seems interesting and I like the simplicity vs Ash Framework which is AMAZING but feels like learning yet another framework on elixir, and this feels more lightweight
